### ISSUE TITLE
Multiple questions about the usage

### ISSUE THREAD

**Issue by TGP17** [janithcooray/lin_os_swap_mod#17]
Hey, I have some questions regarding how to use it. Question 1: Would this also work on Pixel Experience?

Question 2: What do I need to flash, the lin_os_swapmod or the swapfile_mod?

Question 3: If I disable and remove the module would everything return to the way it was configured before or would it permanently change things on my Phone? I want to see if it works on my Phone, but I don't want to risk breaking my current ROM Installation, as I could disable the Magisk Module incase it boot loops, but I want to be sure that this would actually work.

**Comment by janithcooray** [comment]
## Question 1
Should work fine.

## Question 2
lin_os_swapmod or the swapfile_mod are both the same file, 1 is for legacy a download link

## Question 3
If you disable the module and reboot, it will delete the swap file it created and unregister itself from the boot service. if remove without disabling (rm -rf module/dir) it will no longer register the additional SWAP memory, but the swapfile itself will remain in your data/ directory
