### ISSUE TITLE
"Copying zip to temp directory - Unzip error" in Magisk

### ISSUE THREAD

**Issue by Gooberpatrol66** [janithcooray/lin_os_swap_mod#18]
I downloaded https://github.com/janithcooray/lin_os_swap_mod/archive/refs/tags/v1.3.1-2.zip
Also tried 1.3.1 and 1.3
I have 8G of free space

**Comment by janithcooray** [comment]
hi that's the source code. the other artifacts contain the installable files ->  https://github.com/janithcooray/lin_os_swap_mod/releases/download/v1.3.1-2/swapfile_mod.zip

**Comment by Gooberpatrol66** [comment]
That worked, thanks
