### ISSUE TITLE
Clarify language in readme and script

### ISSUE THREAD

**Issue by PowerUser64** [janithcooray/lin_os_swap_mod#19]
The readme and script both have language that seems to indicate that the script will increase (add to) the current swapfile size by the selected size.

In the readme, it says "...enables or increases the SWAP memory..."
https://github.com/janithcooray/lin_os_swap_mod/blob/4c73bd55308ccd450a7c140146bca0f43a12d4ec/README.md?plain=1#L8
and in the script it says `Vol Up += 8GB` and `Vol Down += 4GB`, as if it's adding to and setting the swapfile size with common C programming operators.
https://github.com/janithcooray/lin_os_swap_mod/blob/4c73bd55308ccd450a7c140146bca0f43a12d4ec/module/customize.sh#L25-L26

However, this is not true. Reading into the source, volume up and down changes `SWAP_BIN_SIZE` to specific values, which are not changed, and are instead directly used to set the size of the new swapfile.
https://github.com/janithcooray/lin_os_swap_mod/blob/4c73bd55308ccd450a7c140146bca0f43a12d4ec/module/customize.sh#L27-L33
https://github.com/janithcooray/lin_os_swap_mod/blob/4c73bd55308ccd450a7c140146bca0f43a12d4ec/module/customize.sh#L57-L62

It's possible this language is used in other places too (like descriptions in module repos). In all cases it should be rephrased to more clearly state that the module creates a swapfile with a size of either 4GB or 8GB.

---

If I'm wrong and the module is actually _supposed_ to add more swap, then language should still be clarified in the module.prop, which conflicts with the aforementioned descriptions, implying that it allows you to change the swap size (as in replace the current value), which is a narrower meaning than is currently presented.

https://github.com/janithcooray/lin_os_swap_mod/blob/d3de2b4c5837029a5b1b99ca63b132a4955a5972/module/module.prop#L6

**Comment by janithcooray** [comment]
SWAP memory is the sum. Your ROM may include its own swap which is managed by your ROM. The SWAP_BIN_SIZE is specific to this module. If you already have 2GB of swap (Added outside this module), and you add 4GB from this module, the swap memory increases to 6GB. If you did not have swap memory prior to this module, it will Enable and set the existing Swap memory to 4/8GB. Which is what i have stated "enables or increases the SWAP memory". 

I'm not sure why are confused with the operators ideology,
```sh
Vol Up += 8GB # 
# If your current swap size was 2GB, 2+=8 = 10GB
# If your current swap size was 0, 0+=8 = 8GB
```

```implying that it allows you to change the swap size (as in replace the current value``` It does, since the Swap memory value is changed (a total of X to X +Y).

**Comment by PowerUser64** [comment]
Thank you for explaining. I presumed that the module would try overwriting your existing swap, hence why it's specific to Lineage OS. It could be worth stating in the module description that, "This module creates a new swapfile and mounts it on boot" (or something similar) for added clarity.

**Comment by janithcooray** [comment]
```I presumed that the module would try overwriting your existing swap``` no, it does not overwrite or touch previous swap.  And is not specific to LOS. it was originally built for LOS, works fine other AOSP based ROMs.
