### ISSUE TITLE
Swap priority

### ISSUE THREAD

**Issue by LostCat123** [janithcooray/lin_os_swap_mod#21]
Is there a way to manually set the value of priority of the the swap, because whatever value I choose the swap always get more priority than the zram

"Set Swap Priority above Zram?"
I chose "yes" and the priority of zram will be at -3 and swap at -2
![Screenshot_20240418-131412](https://github.com/janithcooray/lin_os_swap_mod/assets/91554842/0be1d87c-692c-437b-82ec-c3049ebb5858)

I chose "no" and it zram say -2 with swap on 0
![Screenshot_20240418-192425](https://github.com/janithcooray/lin_os_swap_mod/assets/91554842/192b8bdf-ebba-42fa-951e-15c0023ee9d8)

No matter what I choose, the swap is still prioritized over zram

**Comment by devnoname120** [comment]
Same here, `/dev/block/zram0` has a lower priority than `/dev/swap/swapfile` in `/proc/swaps`.

**Comment by LostCat123** [comment]
> Same here, `/dev/block/zram0` has a lower priority than `/dev/swap/swapfile` in `/proc/swaps`. I use the following module for zram so the problem may be that: https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module
> 
> On a side note it would be great if this module could do both zram and swap so we don't need two modules which can potentially conflict with each other.

The creator of that module added the ability to change zram priority now so I think it should be fine

**Comment by devnoname120** [comment]
I confirm that this update fixed it:

```
% sudo cat /proc/swaps
Filename                                Type            Size       Used    Priority
/data/swap/swapfile                     file            8388604    179968  -2
/dev/block/zram0                        partition       2097148    2034584 0
```

**Comment by janithcooray** [comment]
Ive pushed a couple of option in the latest release. see if that helps
