### ISSUE TITLE
Volume keys didn't work when flashed. Questions. Screenshot inside.

### ISSUE THREAD

**Issue by DB9-max** [janithcooray/lin_os_swap_mod#3]
I tried install twice volume keys didn't work but it installed it in few seconds. So this is it is it ok for this phone?

![Screenshot_20231209-155839~2](https://github.com/janithcooray/lin_os_swap_mod/assets/82726385/f6007857-fb5a-446f-9648-8d16c8db5c68)

![Screenshot_20231209-161223~2](https://github.com/janithcooray/lin_os_swap_mod/assets/82726385/877c981c-f16d-45ca-8236-31e14323bf0f)

Oneplus Nord N100, A11, OxygenOS 

Also can these other two modules interfere with your swap?

**Comment by janithcooray** [comment]
Volume keys won't work for all devices. when it doesn't work , it will default to 4GB. everything will work fine even if the keys are not detected.

New Update will have keys removed with downloadable options instead.

**Comment by janithcooray** [comment]
zip file based on size added. release pending.
