### ISSUE TITLE
Any update for module?

### ISSUE THREAD

**Issue by erfan2255** [janithcooray/lin_os_swap_mod#4]
Hi, actually I liked your module and wanted to know if there will be update for it? thx

**Comment by janithcooray** [comment]
@erfan2255 Thank you for showing interest! I have 2 updates planning to roll out 1 this month for additional sizes and the other 1 1st week of next month for better support with apps

**Comment by traversone** [comment]
any update on this topic?

**Comment by IzzySoft** [comment]
@janithcooray your [module.prop](https://github.com/janithcooray/lin_os_swap_mod/blob/main/module/module.prop) says `version=v1.4`, but the corresponding release is missing. Maybe you forgot to create it? Could you please do so (and also attach the corresponding ZIP to it)? Thanks a lot!

**Comment by janithcooray** [comment]
Hi, some other changes are pending before 1.4, i get a break to work on this these couple weeks due to some personal matters. ill finish this asap. Thanks!

**Comment by IzzySoft** [comment]
As you have no `update.json`, the updater in the IoD Magisk repo has to construct the download link itself. For that, it uses the pattern

`https://github.com/janithcooray/lin_os_swap_mod/releases/download/%v/lin_os_swap_mod.zip`

where `%v` stands for the `version` from the `module.prop`. Unfortunately, that does not correspond to what the tag name really uses, and the real URL to the ZIP is

`https://github.com/janithcooray/lin_os_swap_mod/releases/download/v2.0-a6/lin_os_swap_mod.zip`

Your `module.prop` has

```
version=v2.0-a
versionCode=8
```

Where does the `6` in the tag name come from? How can we solve this? Ideally, you'd have an `update.json` giving these details. For the current release, it would look like:

```json
{
    "version": "v2.0-a",
    "versionCode": "8",
    "zipUrl": "https://github.com/janithcooray/lin_os_swap_mod/releases/download/v2.0-a6/lin_os_swap_mod.zip",
    "changelog": ""
}
```

If you don't want that, could you make the `version` in your `module.prop` matching the tag name? To close the gap (as several releases were already missing here) I now updated it manually – but it would be much nicer if the automated updates could be made working.

Thanks in advance!

**Comment by janithcooray** [comment]
Hi @IzzySoft i had no idea about this implementation regarding update.json. since at the time i checked, i could not find the details for the update proccess on magisk repos, let alone submit it. i will implement the update.json. Thank you for pointing it out.

``Where does the 6 in the tag name come from?`` it's to be changed on build inside the build.sh. i moved it there to make it easier to build on pipelines.

**Comment by IzzySoft** [comment]
> i will implement the update.json. Thank you for pointing it out.

Thank you! So there should be an `update.json` now in a directory called `/release` – but neither file nor directory exist in `main`. Maybe they only exist locally on your machine, and were forgotten to `git add` and `git push`?

As for the `6`: Thanks for the explanation! I just wondered what it relates to, as it seems to be a little off `versionCode`. But then, as soon as the `update.json` is available, that's no longer important for me, as I'd no longer have to construct the `zipUrl` myself for automated updates :wink:

**Comment by janithcooray** [comment]
@IzzySoft according to the docs, i have to point the path to update.json. i have pointed each each update to thier reevant versions. i thought this would work..

```prop
version=v2.0-b
versionCode=9
updateJson=https://github.com/janithcooray/lin_os_swap_mod/releases/latest/download/4096_60_99999.json
```

**Comment by IzzySoft** [comment]
And that's a "stable URL" (which will remain the same with future releases)? I mean, "latest" is a moving target, but that would at least always point to the latest release. I'm more worried about the `4096_60_99999.json`, as the numeric name doesn't sound like it will stay.

May I suggest to place that as `update.json` into the project root? That's where it's usually located (which is also why I didn't look for it at "releases" – I've never encountered it there yet :see_no_evil:).

**Comment by janithcooray** [comment]
@IzzySoft some variables of the varient differ from each other. the numeric name represents the config. 

```May I suggest to place that as update.json into the project root?```
this doesnt sound right with the specs of what the docs say. update.json should point to its latest zip file. 4096_60_99999 should point to its latest version - which is not the same as 4096_80_99999. that is why i have added an update json per config here.

**Comment by IzzySoft** [comment]
Ah, wait: there are so many variants! :scream: So what is the `lin_os_swap_mod.zip` then? That and `swapfile_mod.zip` have no accompanying `*.json`, and are not mentioned in the readme.

Apologies for the confusion on my end, I should have read the Readme more carefully. But I cannot put all the variants into [my Magisk repo](https://apt.izzysoft.de/magisk) (especially not as they all have the same Id), so I'd need to pick one. Currently, `lin_os_swap_mod.zip` is present there. Would that be OK? Or would you prefer a different variant? Or should I rather remove it altogether, to avoid confusion/issues?

**Comment by janithcooray** [comment]
Hi @IzzySoft ill look into this more to figure out what can be done. lin_os_swap_mod and swapfile_mod is a legacy alias to 1 specific config. i would suggest using 4096_60_auto.json as the default as that goes with the 2 legacy zips, at least for the time being. but give me some more time to figure out a better approach to this.

**Comment by janithcooray** [comment]
moving issues as #32

**Comment by IzzySoft** [comment]
Thanks a lot! Waiting for your next ping then – from the other issue :wink: To make sure I don't miss it, I'll go and subscribe "over there".

**Comment by lesching2014** [comment]
@janithcooray you can try create optional.prop file in /sdcard to simplify your codes like https://github.com/reiryuki/ZRAM-Swap-Configurator-Magisk-Module
