### ISSUE TITLE
Please fix typos in customize.sh

### ISSUE THREAD

**Issue by vochong** [janithcooray/lin_os_swap_mod#5]
- In the line ui_print "- Crating a swpafile of $SWAP_BIN_SIZE MB", "Crating" should be corrected to "Creating",  and "swpafile" to "swapfile".

- In the line ui_print "- Please keep the screen on during installtion", "installtion" should be corrected to "installation".

**Comment by janithcooray** [comment]
@vochong  Thank you for pointing it out, will fix it asap.

**Comment by janithcooray** [comment]
Fixed on 1.3.1
