### ISSUE TITLE
unzip errror

### ISSUE THREAD

**Issue by Hacker979** [janithcooray/lin_os_swap_mod#8]
Unzip error

**Comment by janithcooray** [comment]
Hi Could you please provide more information, maybe a screenshot ?

**Comment by Hacker979** [comment]
It’s just that when installing the latest version you can’t install it, you can install the penultimate one 
![Screenshot_20240119-083436_Kitsune Mask](https://github.com/janithcooray/lin_os_swap_mod/assets/75617199/89106c97-6e8d-4d67-8c74-e7090edb8705)


> Привет. Не могли бы вы добавить дополнительную информацию, может быть, скриншот?

**Comment by janithcooray** [comment]
There was an issue with the link earlier, could be the reason. try this - https://github.com/janithcooray/lin_os_swap_mod/releases/download/v1.3/lin_os_swap_mod.zip
