### ISSUE TITLE
zip file

### ISSUE THREAD

**Issue by pommie65** [janithcooray/lin_os_swap_mod#9]
Hi,

Thanks for the great work.
I'm rather new to all this so please be patient with my following question.
Where can i find the zip file to install the module?

On https://xdaforums.com/t/mod-swapfile-mod-7-0-magisk-module.4607727/ page the download links deliver a "not found" message.

Thanks,
Take care,
Robert

**Comment by pommie65** [comment]
forgot to mention that on https://xdaforums.com/t/mod-swapfile-mod-7-0-magisk-module.4607727/ page the download links delivera "not found" message.

**Comment by janithcooray** [comment]
Sorry my bad, Fixed the link on xda asap -https://xdaforums.com/t/mod-swapfile-mod-7-0-magisk-module.4607727/

Download 
https://github.com/janithcooray/lin_os_swap_mod/releases/download/v1.3/lin_os_swap_mod.zip
